name: test pytorch on mac

on:
  push:
    branches:
      - main
    tags:
      - "*-[0-9]+.*"
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-11]
      fail-fast: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '11'
    - name: Generate Classpath (Unix)
      run: |
        mvn clean install org.apache.maven.plugins:maven-shade-plugin:3.2.4:shade -Dshade.mainClass=io.bioimage.modelrunner.pytorch.PytorchInterface

    - name: Write Version to File
      run: |
        echo "$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" > version.txt
        echo "JAR_PATH=target/dl-modelrunner-$(cat version.txt).jar" >> $GITHUB_ENV

    - name: Run Specific Class (Unix)
      shell: bash
      run: |
        java -cp dl-modelrunner-pytorch-0.4.3-SNAPSHOT.jar io.bioimage.modelrunner.pytorch.PytorchInterface
